[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[dev]
  command = "npm run start"
  port = 3000
  targetPort = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

  