[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"

[dev]
  command = "npm run start"
  port = 3000
  targetPort = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 